apiVersion: v1
kind: Pod
metadata:
  name: gpu-nvidia-smi
spec:
#  nodeSelector:
#    karpenter.sh/nodepool: gpu-g6f
  tolerations:
    - key: "nvidia.com/gpu"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
  containers:
    - name: nvidia-smi
      image: nvidia/cuda:12.4.1-base-ubuntu22.04
      command: ["bash","-lc","nvidia-smi && sleep 3600"]
      resources:
        limits:
          nvidia.com/gpu: 1
