secret:
    data:
        redis-password: ENC[AES256_GCM,data:e/5WusiQMvkAbrTTpggsMu4JaoOqMTm2uKXbTyvVa1WN7d8hkyNODm9ova8=,iv:aSViZdPJAYvAr0RS1qhrWI+BCMzkX63F4WBagk2yA0M=,tag:ObnbpPX7CJDIuSWSkobXPA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-2:577124901432:key/ee087b6b-0148-47d9-a91f-701237f25dae
          created_at: "2025-12-06T07:09:47Z"
          enc: AQICAHjPEo2yeK1UDnFVjMsadc6jZpXMWiwPGnckDXPQhghg2gFfkzNeVTufN/J9g0PG5ca8AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMb1pwIDDRcRs5Vki/AgEQgDv9jAoYk/Fx/gtuyJPjZbwgeoXcwZseD7N7dsrGcNaUgljuvB3LHil5Qa5MNfVVYpsSKRcJ9Yt1w6Povg==
          aws_profile: ""
    lastmodified: "2025-12-15T18:32:52Z"
    mac: ENC[AES256_GCM,data:0iEJU2rhuvhow+IXhLKgAU8KAMUs2MxNqit9AEzy/pEr1lnE4RNiWCUv72v5X/woPNZMvLwtQeuCdF/B1KUvxt2xzYkF3jE7tEr54Xfah2s0T+Gi1eEXTeD7e4nMQ8aE5pD9eW4oy5No0Zl9XSO8EOlYaAfZgytNHJZ+2Pmg30A=,iv:rtmOVOsNYZh8y2r/qC1hn4kFWVRy7eN5PZ6OyHu/XDI=,tag:RsvW+PdrN3sXX03OTNTLgg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
