secret:
    data:
        redis-password: ENC[AES256_GCM,data:jeLgiiH95Q3fI76tWEMflS11rhdz7Ng0Z7tLPzWw4Yjbqbaw3cZmnpwgsY4=,iv:XFLVnSGoMYEOeLNj0ll88Aox293FH/3IT28tyS6aG9M=,tag:mOCRL+/K6f5lK2qCofEIPw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-2:577124901432:key/ee087b6b-0148-47d9-a91f-701237f25dae
          created_at: "2025-12-06T06:46:18Z"
          enc: AQICAHjPEo2yeK1UDnFVjMsadc6jZpXMWiwPGnckDXPQhghg2gGBbjRs1MX0XcMH7RkYWzISAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM+WLmkflBUELhaP7jAgEQgDuLZDmXZlzE2/9Xi6IiXcB3oDia1aa1PlJ7PuMhEMWEXj0ArL7jWQBEvZfwxDFWDi5DQFDancSfZ44r1g==
          aws_profile: ""
    lastmodified: "2025-12-15T07:17:13Z"
    mac: ENC[AES256_GCM,data:PFXeOUv7Wjw5Lv7hom8m90VW/6Ma+8c8i2NWHPRFvcKzTW3gh/E7Kp2ofR3s52SB+5+X4v3AkCvuSe3ilc90w1QJCfwOESHJ9mxrG8aF1jUDJ5jBRE3z8EIz6Bibc2ICZJ/bD0cWUD0Gpq20bA6WdDXW3OLqctPqx7CgkVOfy7c=,iv:vAUKX9BWjIrc0RZvdJab4m6DcjrciZ/kS8cmB7pO+FY=,tag:oVqn2Oe3wTNMwIvbU+kUXQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
