{{- if .Values.secret.data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis.secretName" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
type: Opaque
data:
  {{- toYaml .Values.secret.data | nindent 2 }}
{{- end }}
