{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "pipecat-daily-bot.fullname" . }}
  labels:
    {{- include "pipecat-daily-bot.labels" . | nindent 4 }}
{{- end }}
