{{- if .Values.secret.data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name | default (include "pipecat-daily-bot.fullname" .) }}
  namespace: {{ include "pipecat-daily-bot.fullname" . }}
  labels:
    {{- include "pipecat-daily-bot.labels" . | nindent 4 }}
type: Opaque
data:
  {{- toYaml .Values.secret.data | nindent 2 }}
{{- end }}
