secret:
    data:
        MESH_SHARED_SECRET: ENC[AES256_GCM,data:tZe6VApc6Y/MmxKNC+6HJ6G8ijFtdY5z16QK0G4Mn0R/+vrCrHS62vuJCGc=,iv:L70qqmzH0VwGed8ff6DYL9kPqJl9nF5LM4ayWLUpJ10=,tag:0rgPCE3wpvD/nSLZDeNY7w==,type:str]
        POSTGRES_PASSWORD: ENC[AES256_GCM,data:r42i1USWYvM5oeD0MwU5406V0t2yDzEdy9SKg0tOOg1tjMoKONmEew==,iv:dB21aEGCsWxzvvRGTRcifGLCUIjav2XaY3gH+VUQ4fI=,tag:6QIe0OvqR/qlGmDJOJUXfQ==,type:str]
        POSTGRES_USER: ENC[AES256_GCM,data:Kjh7DrT9lxIvn6gC,iv:uAA1TUOvmZbcvvVQ4p1QH1PV/WQhtN46X0YmhksW8kk=,tag:Hp+F05ZoWIQz0MznKTifVg==,type:str]
        REDIS_PASSWORD: ENC[AES256_GCM,data:SlWdOmP0WXAd2/NKPnzVpTVs/v+jaOpoSTLwvgApzDzh/ZF31DtN44U3sMI=,iv:2vtfm+lmFbl3x33Uc+wuhPnbwcBWmOEPtcB4kADSuPU=,tag:zM29QtP7Jugg3YSNEM9RiQ==,type:str]
        REDIS_SHARED_SECRET: ENC[AES256_GCM,data:k9bX/SHB71Fd48EOnIRnbcnJdYmuQi/xyuWOGBGC9/PhUurKzziFtFumxdE=,iv:vu0PBeaewCJl4d17au62hyg/kyYscTeXmO4+WO1kL5c=,tag:LYu1KzI1KOWEdWjEUm2AbA==,type:str]
        TOKEN_ENCRYPTION_KEY: ENC[AES256_GCM,data:cI4apF93Kj9Z+M33Lj2IIvsWgGNMylPCteGcfpr1tllhqepAF5kuGGDr+i4=,iv:ZxKPbjtTROOsk8YX9xjGrNWa7/GD7WqIbS5SSUSAU78=,tag:pg4LGVqYufdFtF/GXpQH1A==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-2:577124901432:key/ee087b6b-0148-47d9-a91f-701237f25dae
          created_at: "2025-12-06T07:09:45Z"
          enc: AQICAHjPEo2yeK1UDnFVjMsadc6jZpXMWiwPGnckDXPQhghg2gGuB++6aRBp216Obli6IoIyAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMdusWCY3HIgTJDk5zAgEQgDvTXSmq10nNsAkjuMjNNQNGoYhzex5PvEdeDaz1No67/t0ByuOWzBjYNVTJzGKbNi2W7S4TLoeT8M6pEQ==
          aws_profile: ""
    lastmodified: "2025-12-15T19:40:20Z"
    mac: ENC[AES256_GCM,data:EPTLaNmR2fdmJGAL08mrNAuKEalVLsTiZEPjykkHaLHv8vpZHLGDzluKsGW1sU3vAxyMYeqhWIoqMbpzx/VW7qyl1OBti691aIN8sVaa7lDGy4hkMR6i6cHy1bcmjbdJAC++439tZXZIggylMLycpLXB23BM9y06h5wKIa2qZ3o=,iv:SOcjEGWv+h3QzfdHIDqcQsjWZL54SSiqImi8oosBoPY=,tag:sEL72WsTVcXKPZM10eNxIA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
